version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /
    target-branch: main
    schedule:
      interval: weekly
    ignore:
      - dependency-name: chai
        update-types:
          - version-update:semver-major
  - package-ecosystem: gitsubmodule
    directory: /
    target-branch: main
    schedule:
      interval: daily
