name: Test coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  Coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4.0.0
      - name: Set up with Node.js LTS
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v4.0.1
        with:
          node-version: lts/*
      - name: Download dependencies
        run: npm ci
      - name: Generate coverage report
        run: npm run coverage
      - name: Upload coverage to Quality
        if: github.event_name == 'push'
        uses: qltysh/qlty-action/coverage@fd52dc852530a708d68c3b7342f8d33d1df4cd55 # v1.0.0
        with:
          oidc: true
          files: coverage/lcov.info
